language: node_js
node_js: "8"
sudo: false

env:
  matrix:
    - YARN_CMD=lint
    - YARN_CMD=test
    - YARN_CMD=ci-test-integrations
  global:
    - MONGODB=3.4.16
    - APP_SECRET=44E52D2227F93179525E252EC3AB5
install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz
  - tar xzf mongodb-linux-x86_64-${MONGODB}.tgz
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - cp .env.example .env
  - cp .env.example .env.test
  - yarn

services:
  - redis-server

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - touch .env

before_script:
  - mkdir ${PWD}/mongodb-linux-x86_64-${MONGODB}/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/data --logpath ${PWD}/mongodb-linux-x86_64-${MONGODB}/mongodb.log --fork

cache:
  yarn: true
  directories: 
    - api/src/node_modules/
    - cli/src/node_modules/
    - ui/src/node_modules/
    - worker/src/node_modules/

script:
  - yarn $YARN_CMD

after_script:
  - pkill mongod

after_success:
  - yarn semantic-release
