version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: mongo:4.2-bionic
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: redis:4-alpine
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    environment:
      TERM: xterm
      MONGODB_PATH: mongodb://127.0.0.1:27017/ll_integration_test
      MONGODB_TEST_PATH: mongodb://127.0.0.1:27017/ll_tests
      QUEUE_PROVIDER: REDIS
      REDIS_HOST: 127.0.0.1
      API_HOST: 127.0.0.1
      API_PORT: 8080
      TEST_API_PORT: 8080
      UI_HOST: 127.0.0.1
      UI_PORT: 3000
      APP_SECRET: 44E52D2227F93179525E252EC3AB5
      SITE_URL: "http://127.0.0.1:3000"
      TEST_LOG_MIN_LEVEL: info
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Installing Dependencies
          command: npm_config_build_from_source=true yarn --ignore-engines
      - run:
          name: Create empty .env
          command: touch .env
      - run:
          name: Testing Compile
          command: yarn run build-all
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run linter
          command: yarn run lint-ci
      - run:
          name: Run tests
          command: yarn run test
      - deploy:
          name: Semantic Release
          command: yarn run semantic-release

workflows:
  build:
    jobs:
      - build:
          context:
            - docker-hub-creds
