version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
      - image: mongo:3.4-jessie
      - image: redis:4-alpine
    environment:
      TERM: xterm
      MONGODB_PATH: mongodb://localhost:27017/ll_integration_test
      MONGODB_TEST_PATH: mongodb://localhost:27017/ll_tests
      QUEUE_PROVIDER: REDIS
      REDIS_HOST: 127.0.0.1
      API_HOST: 127.0.0.1
      API_PORT: 8080
      TEST_API_PORT: 8080
      UI_HOST: 127.0.0.1
      UI_PORT: 3000
      APP_SECRET: 44E52D2227F93179525E252EC3AB5
      SITE_URL: "http://127.0.0.1:3000"
      TEST_LOG_MIN_LEVEL: info
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-cache-{{ .Branch }}-{{ .Revision }}
            - v3-cache-{{ .Branch }}
            - v3-cache
      - run:
          name: Installing Dependencies
          command: yarn install
      - run:
          name: Create empty .env
          command: touch .env
      - run:
          name: Testing Compile
          command: yarn run build-all
      - save_cache:
          key: v3-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - node_modules
            - api/src/node_modules/.cache
            - ui/src/node_modules/.cache
            - cli/src/node_modules/.cache
            - worker/src/node_modules/.cache
            - ~/.cache/yarn
      - run:
          name: Run linter
          command: yarn run lint
      - run:
          name: Run tests
          command: yarn run test
      - deploy:
          name: Semantic Release
          command: yarn run semantic-release
